export const MIRKVALE_REGION_ID = "mirkvale";


export const MIRKVALE_LOCATION_PROFILES = {
  elarion: {
    id: "elarion",
    name: "Elarion",
    title: "The Capital of Elfs",
    lore: [
      "Elarion",
      "",
      "The Capital of Elfs",
      "",
      "The silver crown of the forest.",
      "A city of towers, still waters, and authority spoken in calm voices.",
      "",
      "Elarion stands as the capital of Mirkvale and the most revered city of the elfs. Built among ancient trees and pale stone terraces, it rises with elegance rather than force, shaped to follow the land instead of conquering it. Bridges of carved wood and silver-veined marble connect its halls, and moonlight seems to linger there longer than in other places.",
      "",
      "The city is a seat of wisdom, ceremony, and guarded power. Here, ancient houses weigh old obligations against present need, and every public grace conceals careful judgment. Elarion welcomes few without purpose, for it is not merely a capital. It is a place where memory itself is treated as law.",
    ].join("\n"),
  },
  silvergrove: {
    id: "silvergrove",
    name: "Silvergrove",
    title: "Council of Elders",
    lore: [
      "Silvergrove",
      "",
      "Council of Elders",
      "",
      "A sacred seat of judgment beneath the trees.",
      "Where the eldest voices of Mirkvale speak for the realm.",
      "",
      "Silvergrove is the gathering place of the elder council, a grove-hall where the oldest and most respected voices of Mirkvale meet to deliberate matters of law, tradition, and the survival of the realm. Rather than a single chamber, it is a living place of ancient trees, carved platforms, and open sanctuaries where nature and authority are bound together.",
      "",
      "The council's power is quiet but absolute. Decisions made in Silvergrove shape noble houses, border policy, sacred rites, and the realm's stance toward outsiders. Many in Mirkvale speak of the place with reverence. Others speak of it with caution, for old wisdom can become as unyielding as old stone.",
    ].join("\n"),
  },
  "the-silver-lake": {
    id: "the-silver-lake",
    name: "The Silver Lake",
    title: "Holy and Sacred Lake",
    lore: [
      "The Silver Lake",
      "",
      "Holy and Sacred Lake",
      "",
      "A mirror of moonlight and silence.",
      "A place of ritual, reflection, and beauty too pure to disturb.",
      "",
      "The Silver Lake is one of the holiest places in all Mirkvale. Its waters are unnaturally clear, often reflecting moon and stars with such perfection that many believe the lake holds a veil between the mortal world and something older beyond it. Pilgrims, priests, and nobles alike come there to pray, meditate, and take part in ancient rites of purification and remembrance.",
      "",
      "No settlement crowds its shores. The lake is protected by custom, reverence, and strict decree, and few are permitted to approach it carelessly. To the elfs, it is more than water. It is memory made visible. Those who stand before it for long often leave quieter than they arrived.",
    ].join("\n"),
  },
  thornveil: {
    id: "thornveil",
    name: "Thornveil",
    title: "The Blacksmith of Silver",
    lore: [
      "Thornveil",
      "",
      "The Blacksmith of Silver",
      "",
      "A place of flame, craft, and disciplined mastery.",
      "Where beauty and war are forged by the same hand.",
      "",
      "Thornveil is the most renowned smithing seat in Mirkvale, a workshop-settlement known for the forging of silver arms, ceremonial armor, fine tools, and heirlooms of astonishing precision. Unlike the harsher forges of dwarfs or men, Thornveil is shaped by elegance and control, where every strike of the hammer is measured as carefully as a line of poetry.",
      "",
      "Its craft is held in the highest esteem. Weapons made in Thornveil are not produced in great number, but each carries meaning beyond utility. To bear silver forged there is to carry a piece of elven pride, art, and heritage. Few masters are welcomed into its deeper halls, and fewer still leave with all they hoped to learn.",
    ].join("\n"),
  },
  "ithariels-grove": {
    id: "ithariels-grove",
    name: "Ithariel's Grove",
    title: "Seat of House Pure-Blood",
    lore: [
      "Ithariel's Grove",
      "",
      "Seat of House Pure-Blood",
      "",
      "An ancient noble seat among untouched green.",
      "Beautiful, refined, and burdened by the weight of lineage.",
      "",
      "Ithariel's Grove is the ancestral home of House Pure-Blood, one of the oldest and most tradition-bound noble lines in Mirkvale. Hidden among ancient trees and pale pavilions, it appears serene from afar, almost like part of the forest itself. Yet within its halls, bloodline, status, and inheritance are treated with deadly seriousness.",
      "",
      "House Pure-Blood represents the old heart of Mirkvale's nobility: proud, disciplined, and unwilling to let go of ancient distinctions. Its influence reaches deep into court, council, and custom, but so too does its reputation for cold judgment. Many admire Ithariel's Grove as a symbol of elven grandeur. Many others see it as a place where purity is valued above peace.",
    ].join("\n"),
  },
  "the-whispering-forest": {
    id: "the-whispering-forest",
    name: "The Whispering Forest",
    title: "The Ancient Forest",
    lore: [
      "The Whispering Forest",
      "",
      "The Ancient Forest",
      "",
      "The oldest part of Mirkvale.",
      "A forest of living memory, hidden paths, and voices carried on the leaves.",
      "",
      "The Whispering Forest stretches beyond mapped certainty, forming the deepest and most ancient reaches of Mirkvale. Its trees are vast, its paths shifting, and its silence is never complete. The wind there moves strangely through branch and root, carrying sounds that many claim resemble distant voices speaking in tongues both familiar and long forgotten.",
      "",
      "To the elfs, the forest is sacred, feared, and deeply respected. It is said to remember every trespass and every oath spoken beneath its canopy. Rangers, mystics, and wardens walk its hidden ways, but never without caution. For all its beauty, the Whispering Forest is not tame land. It is old power, still watching.",
    ].join("\n"),
  },
};

