import {
  ARMOR_CLASS,
  EQUIPMENT_FAMILY,
  ITEM_CATEGORY,
  ITEM_LOOT_SOURCE,
  ITEM_RARITY,
  ITEM_SLOT,
} from "./constants";

function defineItem(item) {
  return {
    stackable: false,
    maxStack: 1,
    lootable: false,
    lootSources: [],
    lootTierRange: { min: 1, max: 5 },
    marketIds: [],
    marketRules: { buy: false, sell: true },
    effects: {},
    inventorySize: { width: 1, height: 1 },
    ...item,
  };
}

export const ITEM_CATALOG = [
  defineItem({
    id: "iron-sword",
    name: "Iron Sword",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.COMMON,
    slot: ITEM_SLOT.WEAPON,
    family: EQUIPMENT_FAMILY.SWORD,
    weight: 8,
    price: 25,
    description: "Reliable steel blade for frontline fighters.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        strength: 2,
      },
    },
    inventorySize: { width: 1, height: 3 },
  }),
  defineItem({
    id: "tower-shield",
    name: "Tower Shield",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.COMMON,
    slot: ITEM_SLOT.SHIELD,
    family: EQUIPMENT_FAMILY.TOWER_SHIELD,
    weight: 15,
    price: 34,
    description: "A wall of steel that favors survivability over mobility.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE, ITEM_LOOT_SOURCE.ARENA],
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        constitution: 1,
      },
    },
    inventorySize: { width: 2, height: 3 },
  }),
  defineItem({
    id: "battle-axe",
    name: "Battle Axe",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.EPIC,
    slot: ITEM_SLOT.WEAPON,
    family: EQUIPMENT_FAMILY.AXE,
    weight: 18,
    price: 55,
    description: "Heavy two-handed edge with high raw power.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE, ITEM_LOOT_SOURCE.ARENA],
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        strength: 3,
      },
    },
    inventorySize: { width: 2, height: 4 },
  }),
  defineItem({
    id: "chain-vest",
    name: "Chain Vest",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.ARMOR,
    family: EQUIPMENT_FAMILY.CHAIN_ARMOR,
    armorClass: ARMOR_CLASS.MEDIUM,
    weight: 13,
    price: 38,
    description: "Linked steel rings that improve endurance in hard fights.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE, ITEM_LOOT_SOURCE.ARENA],
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        constitution: 2,
      },
    },
    inventorySize: { width: 2, height: 3 },
  }),
  defineItem({
    id: "leather-armor",
    name: "Leather Armor",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.ARMOR,
    family: EQUIPMENT_FAMILY.LEATHER_ARMOR,
    armorClass: ARMOR_CLASS.MEDIUM,
    weight: 10,
    price: 18,
    description: "Legacy staple armor still available for balanced builds.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["leathermaker-workshop"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        constitution: 2,
      },
    },
    inventorySize: { width: 2, height: 3 },
  }),
  defineItem({
    id: "soft-leather-armor",
    name: "Soft Leather Armor",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.COMMON,
    slot: ITEM_SLOT.ARMOR,
    family: EQUIPMENT_FAMILY.LEATHER_ARMOR,
    armorClass: ARMOR_CLASS.LIGHT,
    weight: 6,
    price: 22,
    description: "Flexible armor that improves agility.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["leathermaker-workshop"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        dexterity: 1,
      },
    },
    inventorySize: { width: 2, height: 3 },
  }),
  defineItem({
    id: "reinforced-leather-armor",
    name: "Reinforced Leather Armor",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.ARMOR,
    family: EQUIPMENT_FAMILY.LEATHER_ARMOR,
    armorClass: ARMOR_CLASS.MEDIUM,
    weight: 9,
    price: 34,
    description: "Layered hide with balanced agility and durability bonuses.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["leathermaker-workshop"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        dexterity: 1,
        constitution: 1,
      },
    },
    inventorySize: { width: 2, height: 3 },
  }),
  defineItem({
    id: "shadow-leather-coat",
    name: "Shadow Leather Coat",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.EPIC,
    slot: ITEM_SLOT.ARMOR,
    family: EQUIPMENT_FAMILY.LEATHER_ARMOR,
    armorClass: ARMOR_CLASS.LIGHT,
    weight: 8,
    price: 63,
    description: "Elite leather armor for high-mobility, high-risk builds.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ARENA],
    lootTierRange: { min: 4, max: 5 },
    marketIds: ["shadow-bazaar", "leathermaker-workshop"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        dexterity: 2,
        wisdom: 1,
      },
    },
    inventorySize: { width: 2, height: 3 },
  }),
  defineItem({
    id: "scout-hood",
    name: "Scout Hood",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.COMMON,
    slot: ITEM_SLOT.HELMET,
    family: EQUIPMENT_FAMILY.HOOD_HELMET,
    weight: 2,
    price: 16,
    description: "Light headgear favored by trackers and scouts.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["leathermaker-workshop"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        wisdom: 1,
      },
    },
    inventorySize: { width: 2, height: 1 },
  }),
  defineItem({
    id: "rune-staff",
    name: "Rune Staff",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.WEAPON,
    family: EQUIPMENT_FAMILY.STAFF,
    weight: 5,
    price: 32,
    description: "Arcane channeling focus for scholars and casters.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE, ITEM_LOOT_SOURCE.ARENA],
    marketIds: ["arcanist-sanctum"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        intelligence: 2,
      },
    },
    inventorySize: { width: 1, height: 4 },
  }),
  defineItem({
    id: "focus-charm",
    name: "Focus Charm",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.RING,
    family: EQUIPMENT_FAMILY.FOCUS_RING,
    weight: 1,
    price: 27,
    description: "Runed charm that sharpens intellect and clarity.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["arcanist-sanctum"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        intelligence: 1,
        wisdom: 1,
      },
    },
    inventorySize: { width: 1, height: 1 },
  }),
  defineItem({
    id: "mind-ring",
    name: "Mind Ring",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.RING,
    family: EQUIPMENT_FAMILY.MIND_RING,
    weight: 1,
    price: 24,
    description: "Subtle arcane ring that boosts social precision and insight.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["arcanist-sanctum"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        charisma: 1,
        wisdom: 1,
      },
    },
    inventorySize: { width: 1, height: 1 },
  }),
  defineItem({
    id: "health-potion",
    name: "Health Potion",
    category: ITEM_CATEGORY.CONSUMABLE,
    rarity: ITEM_RARITY.COMMON,
    slot: ITEM_SLOT.CONSUMABLE,
    stackable: true,
    maxStack: 5,
    weight: 1,
    price: 11,
    description: "Restorative brew intended to recover HP when consumed.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["alchemist-lab"],
    marketRules: { buy: true, sell: true },
    effects: {
      consumable: {
        hpRestore: 8,
      },
    },
    inventorySize: { width: 1, height: 1 },
  }),
  defineItem({
    id: "energy-draught",
    name: "Energy Draught",
    category: ITEM_CATEGORY.CONSUMABLE,
    rarity: ITEM_RARITY.COMMON,
    slot: ITEM_SLOT.CONSUMABLE,
    stackable: true,
    maxStack: 5,
    weight: 1,
    price: 12,
    description: "Concentrated tonic that restores spent Energy.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["alchemist-lab"],
    marketRules: { buy: true, sell: true },
    effects: {
      consumable: {
        energyRestore: 8,
      },
    },
    inventorySize: { width: 1, height: 1 },
  }),
  defineItem({
    id: "focus-tonic",
    name: "Focus Tonic",
    category: ITEM_CATEGORY.CONSUMABLE,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.CONSUMABLE,
    stackable: true,
    maxStack: 5,
    weight: 1,
    price: 16,
    description: "Experimental tonic designed to improve the next activity check.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["alchemist-lab"],
    marketRules: { buy: true, sell: true },
    effects: {
      consumable: {
        activityRollModifier: 2,
      },
    },
    inventorySize: { width: 1, height: 1 },
  }),
  defineItem({
    id: "calm-brew",
    name: "Calm Brew",
    category: ITEM_CATEGORY.CONSUMABLE,
    rarity: ITEM_RARITY.COMMON,
    slot: ITEM_SLOT.CONSUMABLE,
    stackable: true,
    maxStack: 5,
    weight: 1,
    price: 15,
    description: "Cooling draft used to reduce Heat build-up.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["alchemist-lab"],
    marketRules: { buy: true, sell: true },
    effects: {
      consumable: {
        heatReduction: 3,
      },
    },
    inventorySize: { width: 1, height: 1 },
  }),
  defineItem({
    id: "shadow-dagger",
    name: "Shadow Dagger",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.EPIC,
    slot: ITEM_SLOT.WEAPON,
    family: EQUIPMENT_FAMILY.DAGGER,
    weight: 5,
    price: 49,
    description: "Illicit blade made for quick strikes and social leverage.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["shadow-bazaar"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        dexterity: 2,
        charisma: 1,
      },
    },
    inventorySize: { width: 1, height: 2 },
  }),
  defineItem({
    id: "infernal-charm",
    name: "Infernal Charm",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.RING,
    family: EQUIPMENT_FAMILY.INFERNAL_RING,
    weight: 2,
    price: 58,
    description: "Powerful charm that boosts CHA but slowly raises Heat.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE, ITEM_LOOT_SOURCE.ARENA],
    marketIds: ["shadow-bazaar"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        charisma: 2,
      },
      activityDelta: {
        heat: 1,
      },
    },
    inventorySize: { width: 1, height: 1 },
  }),
  defineItem({
    id: "smuggler-pack",
    name: "Smuggler Pack",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.BELT,
    family: EQUIPMENT_FAMILY.UTILITY_BELT,
    weight: 4,
    price: 44,
    description: "Compartment-heavy belt rig that increases carry utility.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["shadow-bazaar"],
    marketRules: { buy: true, sell: true },
    effects: {
      carryCapacity: 9,
      stats: {
        dexterity: 1,
      },
    },
    inventorySize: { width: 2, height: 2 },
  }),
  defineItem({
    id: "blood-talisman",
    name: "Blood Talisman",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.EPIC,
    slot: ITEM_SLOT.GLOVES,
    family: EQUIPMENT_FAMILY.GAUNTLETS_GLOVES,
    weight: 2,
    price: 67,
    description: "A dangerous artifact with strong power and an HP drawback.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE, ITEM_LOOT_SOURCE.ARENA],
    marketIds: ["shadow-bazaar"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        strength: 2,
        wisdom: 1,
      },
      activityDelta: {
        hp: -1,
      },
      activityDeltaOnFailure: {
        heat: 1,
      },
    },
    inventorySize: { width: 1, height: 2 },
  }),
  defineItem({
    id: "arena-laurel",
    name: "Arena Laurel",
    category: ITEM_CATEGORY.TROPHY,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.HELMET,
    family: EQUIPMENT_FAMILY.CROWN_HELMET,
    weight: 2,
    price: 0,
    renownPrice: 10,
    description: "Renown-forged wreath that improves arena performance.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ARENA],
    marketIds: ["trophy-merchant"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        constitution: 1,
        charisma: 1,
      },
      activityRollModifierByActivity: {
        arena: 1,
      },
    },
    inventorySize: { width: 2, height: 1 },
  }),
  defineItem({
    id: "champion-belt",
    name: "Champion Belt",
    category: ITEM_CATEGORY.TROPHY,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.BELT,
    family: EQUIPMENT_FAMILY.CHAMPION_BELT,
    weight: 3,
    price: 0,
    renownPrice: 14,
    description: "Prestige belt awarded to proven contenders.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ARENA],
    marketIds: ["trophy-merchant"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        strength: 1,
        charisma: 1,
      },
    },
    inventorySize: { width: 2, height: 1 },
  }),
  defineItem({
    id: "victors-crest",
    name: "Victor's Crest",
    category: ITEM_CATEGORY.TROPHY,
    rarity: ITEM_RARITY.EPIC,
    slot: ITEM_SLOT.RING,
    family: EQUIPMENT_FAMILY.VICTOR_RING,
    weight: 2,
    price: 0,
    renownPrice: 20,
    description: "High-renown prestige crest for late-game social power.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ARENA],
    marketIds: ["trophy-merchant"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        charisma: 2,
        wisdom: 1,
      },
      activityRollModifierByActivity: {
        arena: 1,
        adventure: 1,
      },
    },
    inventorySize: { width: 1, height: 1 },
  }),
  defineItem({
    id: "knight-blade",
    name: "Knight Blade",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.WEAPON,
    family: EQUIPMENT_FAMILY.SWORD,
    weight: 10,
    price: 40,
    description: "Tempered longsword with reliable stopping power.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE, ITEM_LOOT_SOURCE.ARENA],
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        strength: 2,
      },
    },
    inventorySize: { width: 1, height: 3 },
  }),
  defineItem({
    id: "warlord-greatsword",
    name: "Warlord Greatsword",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.EPIC,
    slot: ITEM_SLOT.WEAPON,
    family: EQUIPMENT_FAMILY.SWORD,
    weight: 16,
    price: 69,
    description: "Elite two-handed blade for late-stage frontline builds.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ARENA],
    lootTierRange: { min: 4, max: 5 },
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        strength: 3,
      },
    },
    inventorySize: { width: 2, height: 4 },
  }),
  defineItem({
    id: "training-axe",
    name: "Training Axe",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.COMMON,
    slot: ITEM_SLOT.WEAPON,
    family: EQUIPMENT_FAMILY.AXE,
    weight: 7,
    price: 20,
    description: "Basic forged axe built for early STR progression.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        strength: 1,
      },
    },
    inventorySize: { width: 1, height: 3 },
  }),
  defineItem({
    id: "raider-axe",
    name: "Raider Axe",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.WEAPON,
    family: EQUIPMENT_FAMILY.AXE,
    weight: 12,
    price: 46,
    description: "Heavy edge tuned for aggressive arena momentum.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE, ITEM_LOOT_SOURCE.ARENA],
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        strength: 2,
      },
    },
    inventorySize: { width: 2, height: 3 },
  }),
  defineItem({
    id: "scout-dagger",
    name: "Scout Dagger",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.COMMON,
    slot: ITEM_SLOT.WEAPON,
    family: EQUIPMENT_FAMILY.DAGGER,
    weight: 2,
    price: 17,
    description: "Light blade for fast dexterity-oriented builds.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["leathermaker-workshop"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        dexterity: 1,
      },
    },
    inventorySize: { width: 1, height: 2 },
  }),
  defineItem({
    id: "thief-stiletto",
    name: "Thief Stiletto",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.WEAPON,
    family: EQUIPMENT_FAMILY.DAGGER,
    weight: 3,
    price: 35,
    description: "Refined dagger for precision strikes and evasive play.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["shadow-bazaar"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        dexterity: 2,
      },
    },
    inventorySize: { width: 1, height: 2 },
  }),
  defineItem({
    id: "apprentice-staff",
    name: "Apprentice Staff",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.COMMON,
    slot: ITEM_SLOT.WEAPON,
    family: EQUIPMENT_FAMILY.STAFF,
    weight: 4,
    price: 21,
    description: "Starter staff that anchors early intelligence builds.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["arcanist-sanctum"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        intelligence: 1,
      },
    },
    inventorySize: { width: 1, height: 3 },
  }),
  defineItem({
    id: "archmage-staff",
    name: "Archmage Staff",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.EPIC,
    slot: ITEM_SLOT.WEAPON,
    family: EQUIPMENT_FAMILY.STAFF,
    weight: 7,
    price: 72,
    description: "High-tier focus that rewards dedicated caster progression.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ARENA],
    lootTierRange: { min: 4, max: 5 },
    marketIds: ["arcanist-sanctum"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        intelligence: 2,
        wisdom: 1,
      },
    },
    inventorySize: { width: 1, height: 4 },
  }),
  defineItem({
    id: "chain-shirt",
    name: "Chain Shirt",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.COMMON,
    slot: ITEM_SLOT.ARMOR,
    family: EQUIPMENT_FAMILY.CHAIN_ARMOR,
    armorClass: ARMOR_CLASS.MEDIUM,
    weight: 9,
    price: 24,
    description: "Reliable medium armor with balanced defense scaling.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        constitution: 1,
      },
    },
    inventorySize: { width: 2, height: 3 },
  }),
  defineItem({
    id: "chain-hauberk",
    name: "Chain Hauberk",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.EPIC,
    slot: ITEM_SLOT.ARMOR,
    family: EQUIPMENT_FAMILY.CHAIN_ARMOR,
    armorClass: ARMOR_CLASS.HEAVY,
    weight: 16,
    price: 74,
    description: "Battle-forged chainmail for high-end CON and STR builds.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ARENA],
    lootTierRange: { min: 4, max: 5 },
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        constitution: 2,
        strength: 1,
      },
    },
    inventorySize: { width: 2, height: 4 },
  }),
  defineItem({
    id: "recruit-plate",
    name: "Recruit Plate",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.COMMON,
    slot: ITEM_SLOT.ARMOR,
    family: EQUIPMENT_FAMILY.PLATE_ARMOR,
    armorClass: ARMOR_CLASS.HEAVY,
    weight: 12,
    price: 28,
    description: "Entry-level plate with sturdy defensive value.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        constitution: 1,
      },
    },
    inventorySize: { width: 2, height: 3 },
  }),
  defineItem({
    id: "plate-cuirass",
    name: "Plate Cuirass",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.ARMOR,
    family: EQUIPMENT_FAMILY.PLATE_ARMOR,
    armorClass: ARMOR_CLASS.HEAVY,
    weight: 17,
    price: 49,
    description: "Heavy plate shell designed for resilient frontlines.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE, ITEM_LOOT_SOURCE.ARENA],
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        constitution: 2,
      },
    },
    inventorySize: { width: 2, height: 4 },
  }),
  defineItem({
    id: "fortress-plate",
    name: "Fortress Plate",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.EPIC,
    slot: ITEM_SLOT.ARMOR,
    family: EQUIPMENT_FAMILY.PLATE_ARMOR,
    armorClass: ARMOR_CLASS.HEAVY,
    weight: 21,
    price: 85,
    description: "Top-tier heavy armor built for elite endurance encounters.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ARENA],
    lootTierRange: { min: 4, max: 5 },
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        constitution: 2,
        strength: 1,
      },
    },
    inventorySize: { width: 2, height: 4 },
  }),
  defineItem({
    id: "buckler-shield",
    name: "Buckler Shield",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.COMMON,
    slot: ITEM_SLOT.SHIELD,
    family: EQUIPMENT_FAMILY.BUCKLER_SHIELD,
    weight: 5,
    price: 20,
    description: "Compact shield for early defense and controlled mobility.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        constitution: 1,
      },
    },
    inventorySize: { width: 2, height: 2 },
  }),
  defineItem({
    id: "kite-shield",
    name: "Kite Shield",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.SHIELD,
    family: EQUIPMENT_FAMILY.KITE_SHIELD,
    weight: 10,
    price: 37,
    description: "Balanced shield that provides strong mid-tier protection.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE, ITEM_LOOT_SOURCE.ARENA],
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        constitution: 2,
      },
    },
    inventorySize: { width: 2, height: 3 },
  }),
  defineItem({
    id: "bulwark-tower-shield",
    name: "Bulwark Tower Shield",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.EPIC,
    slot: ITEM_SLOT.SHIELD,
    family: EQUIPMENT_FAMILY.TOWER_SHIELD,
    weight: 20,
    price: 78,
    description: "Elite shield wall option with maximum defensive focus.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ARENA],
    lootTierRange: { min: 4, max: 5 },
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        constitution: 2,
        strength: 1,
      },
    },
    inventorySize: { width: 2, height: 4 },
  }),
  defineItem({
    id: "field-helm",
    name: "Field Helm",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.HELMET,
    family: EQUIPMENT_FAMILY.FIELD_HELMET,
    weight: 4,
    price: 32,
    description: "Battle-ready helm tuned for awareness and durability.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        constitution: 1,
        wisdom: 1,
      },
    },
    inventorySize: { width: 2, height: 1 },
  }),
  defineItem({
    id: "war-crown",
    name: "War Crown",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.EPIC,
    slot: ITEM_SLOT.HELMET,
    family: EQUIPMENT_FAMILY.CROWN_HELMET,
    weight: 3,
    price: 66,
    description: "Prestige headpiece with high-level tactical utility.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ARENA],
    lootTierRange: { min: 4, max: 5 },
    marketIds: ["trophy-merchant"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        wisdom: 2,
        charisma: 1,
      },
    },
    inventorySize: { width: 2, height: 1 },
  }),
  defineItem({
    id: "leather-wraps",
    name: "Leather Wraps",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.COMMON,
    slot: ITEM_SLOT.GLOVES,
    family: EQUIPMENT_FAMILY.WRAPS_GLOVES,
    weight: 1,
    price: 14,
    description: "Light hand wraps for baseline dexterity scaling.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["leathermaker-workshop"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        dexterity: 1,
      },
    },
    inventorySize: { width: 1, height: 1 },
  }),
  defineItem({
    id: "duelist-grips",
    name: "Duelist Grips",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.GLOVES,
    family: EQUIPMENT_FAMILY.GRIPS_GLOVES,
    weight: 2,
    price: 29,
    description: "Refined grips that favor agile, precision combat.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["leathermaker-workshop"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        dexterity: 2,
      },
    },
    inventorySize: { width: 1, height: 1 },
  }),
  defineItem({
    id: "war-gauntlets",
    name: "War Gauntlets",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.EPIC,
    slot: ITEM_SLOT.GLOVES,
    family: EQUIPMENT_FAMILY.GAUNTLETS_GLOVES,
    weight: 4,
    price: 64,
    description: "Heavy gauntlets that trade finesse for raw dominance.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ARENA],
    lootTierRange: { min: 4, max: 5 },
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        strength: 2,
        constitution: 1,
      },
    },
    inventorySize: { width: 1, height: 2 },
  }),
  defineItem({
    id: "pathfinder-boots",
    name: "Pathfinder Boots",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.COMMON,
    slot: ITEM_SLOT.BOOTS,
    family: EQUIPMENT_FAMILY.LIGHT_BOOTS,
    weight: 2,
    price: 16,
    description: "Light boots for mobility-focused progression paths.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["leathermaker-workshop"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        dexterity: 1,
      },
    },
    inventorySize: { width: 1, height: 2 },
  }),
  defineItem({
    id: "field-boots",
    name: "Field Boots",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.RARE,
    slot: ITEM_SLOT.BOOTS,
    family: EQUIPMENT_FAMILY.FIELD_BOOTS,
    weight: 3,
    price: 31,
    description: "Sturdy boots for mixed DEX and WIS field play.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["leathermaker-workshop"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        dexterity: 1,
        wisdom: 1,
      },
    },
    inventorySize: { width: 1, height: 2 },
  }),
  defineItem({
    id: "iron-greaves",
    name: "Iron Greaves",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.EPIC,
    slot: ITEM_SLOT.BOOTS,
    family: EQUIPMENT_FAMILY.GREAVES_BOOTS,
    weight: 6,
    price: 62,
    description: "Heavy greaves for late-tier defense with minor mobility.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ARENA],
    lootTierRange: { min: 4, max: 5 },
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        constitution: 2,
        dexterity: 1,
      },
    },
    inventorySize: { width: 1, height: 2 },
  }),
  defineItem({
    id: "utility-belt",
    name: "Utility Belt",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.COMMON,
    slot: ITEM_SLOT.BELT,
    family: EQUIPMENT_FAMILY.UTILITY_BELT,
    weight: 2,
    price: 19,
    description: "General-purpose belt that improves carry handling.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["leathermaker-workshop"],
    marketRules: { buy: true, sell: true },
    effects: {
      carryCapacity: 2,
      stats: {
        strength: 1,
      },
    },
    inventorySize: { width: 2, height: 1 },
  }),
  defineItem({
    id: "warlord-belt",
    name: "Warlord Belt",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.EPIC,
    slot: ITEM_SLOT.BELT,
    family: EQUIPMENT_FAMILY.WARRIOR_BELT,
    weight: 5,
    price: 68,
    description: "High-end belt with carry utility and frontline stats.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ARENA],
    lootTierRange: { min: 4, max: 5 },
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    effects: {
      carryCapacity: 4,
      stats: {
        strength: 2,
        constitution: 1,
      },
    },
    inventorySize: { width: 2, height: 1 },
  }),
  defineItem({
    id: "apprentice-ring",
    name: "Apprentice Ring",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.COMMON,
    slot: ITEM_SLOT.RING,
    family: EQUIPMENT_FAMILY.FOCUS_RING,
    weight: 1,
    price: 18,
    description: "Entry ring with a direct INT boost.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["arcanist-sanctum"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        intelligence: 1,
      },
    },
    inventorySize: { width: 1, height: 1 },
  }),
  defineItem({
    id: "sage-ring",
    name: "Sage Ring",
    category: ITEM_CATEGORY.EQUIPMENT,
    rarity: ITEM_RARITY.EPIC,
    slot: ITEM_SLOT.RING,
    family: EQUIPMENT_FAMILY.MIND_RING,
    weight: 1,
    price: 60,
    description: "Advanced ring with high-value support stat scaling.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ARENA],
    lootTierRange: { min: 4, max: 5 },
    marketIds: ["arcanist-sanctum", "trophy-merchant"],
    marketRules: { buy: true, sell: true },
    effects: {
      stats: {
        wisdom: 2,
        intelligence: 1,
      },
    },
    inventorySize: { width: 1, height: 1 },
  }),
  defineItem({
    id: "iron-ingot",
    name: "Iron Ingot",
    category: ITEM_CATEGORY.MATERIAL,
    rarity: ITEM_RARITY.COMMON,
    stackable: true,
    maxStack: 20,
    weight: 1,
    price: 6,
    description: "Refined crafting material for future forge recipes.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["blacksmith-forge"],
    marketRules: { buy: true, sell: true },
    inventorySize: { width: 1, height: 1 },
  }),
  defineItem({
    id: "cured-hide-roll",
    name: "Cured Hide Roll",
    category: ITEM_CATEGORY.MATERIAL,
    rarity: ITEM_RARITY.COMMON,
    stackable: true,
    maxStack: 20,
    weight: 1,
    price: 6,
    description: "Treated leather stock for future armor crafting.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketIds: ["leathermaker-workshop"],
    marketRules: { buy: true, sell: true },
    inventorySize: { width: 1, height: 1 },
  }),
  defineItem({
    id: "arcane-dust",
    name: "Arcane Dust",
    category: ITEM_CATEGORY.MATERIAL,
    rarity: ITEM_RARITY.RARE,
    stackable: true,
    maxStack: 20,
    weight: 1,
    price: 12,
    description: "Volatile magical residue reserved for advanced crafting.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE, ITEM_LOOT_SOURCE.ARENA],
    marketIds: ["arcanist-sanctum", "alchemist-lab"],
    marketRules: { buy: true, sell: true },
    inventorySize: { width: 1, height: 1 },
  }),
  defineItem({
    id: "torn-banner",
    name: "Torn Banner",
    category: ITEM_CATEGORY.TRASH,
    rarity: ITEM_RARITY.TRASH,
    stackable: true,
    maxStack: 20,
    weight: 1,
    price: 0,
    sellValue: { gold: 1, renown: 0 },
    description: "Damaged battlefield scrap best converted into quick gold.",
    lootable: true,
    lootSources: [
      ITEM_LOOT_SOURCE.QUEST,
      ITEM_LOOT_SOURCE.ADVENTURE,
      ITEM_LOOT_SOURCE.ARENA,
    ],
    marketRules: { buy: false, sell: true },
    inventorySize: { width: 1, height: 1 },
  }),
  defineItem({
    id: "cracked-goblet",
    name: "Cracked Goblet",
    category: ITEM_CATEGORY.TRASH,
    rarity: ITEM_RARITY.TRASH,
    stackable: true,
    maxStack: 20,
    weight: 1,
    price: 0,
    sellValue: { gold: 2, renown: 0 },
    description: "Old metal salvage frequently found after rough contracts.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.QUEST, ITEM_LOOT_SOURCE.ADVENTURE],
    marketRules: { buy: false, sell: true },
    inventorySize: { width: 1, height: 1 },
  }),
  defineItem({
    id: "monster-fang",
    name: "Monster Fang",
    category: ITEM_CATEGORY.TRASH,
    rarity: ITEM_RARITY.TRASH,
    stackable: true,
    maxStack: 20,
    weight: 1,
    price: 0,
    sellValue: { gold: 2, renown: 0 },
    description: "Low-value trophy scrap dropped by dangerous wildlife.",
    lootable: true,
    lootSources: [ITEM_LOOT_SOURCE.ADVENTURE, ITEM_LOOT_SOURCE.ARENA],
    marketRules: { buy: false, sell: true },
    inventorySize: { width: 1, height: 1 },
  }),
];

export const ITEM_CATALOG_MAP = Object.fromEntries(
  ITEM_CATALOG.map((item) => [item.id, item]),
);
